config/routes.rb
Rails.application.routes.draw do
  resources :credit_cards
  resources :addresses
  resources :orders
  resources :categories
  resources :products
  devise_for :users, controllers: { registrations: 'user/registrations' }
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'extra#index'

  get 'show_products', to: 'extra#show_products'
  get 'accounts', to: 'users#index', as: "users"
  get 'my_account', to: 'users#show'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  has_many :orders
  has_one :credit_card
  has_one :address

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def admin?
    self.role == "admin"
  end
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  private

def sign_up_params
  params.require(:user).permit(:email, :password, :password_confirmation, :nume, :adresa, :metoda_plata)
end

def account_update_params
  params.require(:user).permit(:email, :password, :password_confirmation, :current_password, :nume, :adresa, :metoda_plata)
end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin, except: [:show]
   
  def index
      @users = User.all
    end

    def show
      @user = current_user
    if @user.address.nil?
      address = Address.create(user_id: @user.id)
      address.save
      @user.address = address
    end
    if @user.credit_card.nil?
      card = CreditCard.create(user_id: @user.id)
      card.save
      @user.credit_card = card
    end

    @address = @user.address
    @credit_card = @user.credit_card
  end
  end
  

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_address.html.erb
<div class="row mb-4">
  <div class="card mb-4 mb-md-0">
    <div class="card-body">
      <div class="row">
        <div class="col-md-11">
          <h4><% if address.address_type == 'billing' %>
              Billing Address
            <% elsif address.address_type == 'shipping' %>
              Shipping Address
            <% end %>
        </h4>
        </div><br><br>
        <div class="col-md-1">
          <%= link_to "Edit", edit_link, class: "text-success" %>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-4">
          <p class="mb-0">Street Address</p>
        </div>
        <div class="col-sm-8">
          <p class="text-muted mb-0"><%= address.street_address %></p>
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-sm-4">
          <p class="mb-0">City</p>
        </div>
        <div class="col-sm-8">
          <p class="text-muted mb-0"><%= address.city %></p>
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-sm-4">
          <p class="mb-0">State</p>
        </div>
        <div class="col-sm-8">
          <p class="text-muted mb-0"><%= address.state %></p>
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-sm-4">
          <p class="mb-0">Postal Code</p>
        </div>
        <div class="col-sm-8">
          <p class="text-muted mb-0"><%= address.postal_code %></p>
        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-sm-4">
          <p class="mb-0">Country</p>
        </div>
        <div class="col-sm-8">
          <p class="text-muted mb-0"><%= address.country %></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_credit_card.html.erb
<section class="p-4 p-md-5">
  <div class="row d-flex justify-content-center">
    <div class="col-md-10 col-lg-6 col-xl-12">
      <div class="card rounded-3">
        <div class="card-body p-4">
          <div class="text-center mb-4">
            <h3>Credit Cards</h3>
            <h6>Payment</h6>
          </div>
          <% if current_user.present? && credit_card.card_number.present? %>
          <form action="">
            <% if current_user.present? && credit_card.card_number.present? %>
  <form action="">
    <p class="fw-bold mb-4 pb-2">Saved cards:</p>

    <div class="d-flex flex-row align-items-center mb-4 pb-1">
      <% if ['2', '5'].include?(credit_card.card_number.to_s[0]) %>
        <img class="img-fluid" src="https://img.icons8.com/color/48/000000/mastercard-logo.png" />
      <% elsif credit_card.card_number.to_s.start_with?('4') %>
        <img class="img-fluid" src="https://img.icons8.com/color/48/000000/visa.png" />
      <% end %>
      <div class="flex-fill mx-3">
        <div class="form-outline">
          <input type="text" id="formControlLgXc" class="form-control form-control-lg" value="<%= credit_card.card_number %>" />
          <label class="form-label" for="formControlLgXc">Card Number</label>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-6">
        <div class="form-outline mb-4">
          <input type="text" id="cvv" class="form-control" value="<%= credit_card.cvv %>" />
          <label class="form-label" for="cvv">CVV</label>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-outline mb-4">
          <input type="text" id="expiration" class="form-control" value="<%= credit_card.expire %>" />
          <label class="form-label" for="expiration">Expiration Date</label>
        </div>
      </div>
    </div>

    <div class="col-md-2">
      <%= link_to "Edit Card", edit_credit_card_path(credit_card), class: "text-success" %>
    </div>
  </form>
<% else %>
  <div class="col-md-2">
    <%= link_to "Add Card", edit_credit_card_path(credit_card), class: "text-success" %>
  </div>
<% end %>

          </form>
          <% else %>
            <div class="col-md-2">
              <%= link_to "Add Card", edit_credit_card_path(credit_card), class: "text-success" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/users/_creditcard.html.erb
<section class="p-4 p-md-5">
  <div class="row d-flex justify-content-center">
    <div class="col-md-10 col-lg-6 col-xl-12">
      <div class="card rounded-3">
        <div class="card-body p-4">
          <div class="text-center mb-4">
            <h3>Credit Cards</h3>
            <h6>Payment</h6>
          </div>
          <form action="">
            <p class="fw-bold mb-4 pb-2">Saved cards:</p>

            <div class="d-flex flex-row align-items-center mb-4 pb-1">
              <img class="img-fluid" src="https://img.icons8.com/color/48/000000/mastercard-logo.png" />
              <div class="flex-fill mx-3">
                <div class="form-outline">
                  <input type="text" id="formControlLgXc" class="form-control form-control-lg"
                    value="**** **** **** 3193" />
                  <label class="form-label" for="formControlLgXc">Card Number</label>
                </div>
              </div>
              <a href="#!">Remove card</a>
            </div>

            <div class="d-flex flex-row align-items-center mb-4 pb-1">
              <img class="img-fluid" src="https://img.icons8.com/color/48/000000/visa.png" />
              <div class="flex-fill mx-3">
                <div class="form-outline">
                  <input type="text" id="formControlLgXs" class="form-control form-control-lg"
                    value="**** **** **** 4296" />
                  <label class="form-label" for="formControlLgXs">Card Number</label>
                </div>
              </div>
              <a href="#!">Remove card</a>
            </div>
            <%= link_to 'Add Card', new_credit_card_path, class: "btn btn-primary" %>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/users/index.html.erb
<div class="container mt-5">
  <h2>Users</h2>
  <table class="table table-info table-striped">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Email</th>
          <th scope="col">Creation Date</th>
        </tr>
      </thead>
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.id %></td>
            <td><%= user.email %></td>
            <td><%= user.remember_created_at %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
</div>

app/views/users/show.html.erb
<section>
  <div class="container py-5">
    <div class="row">
      <div class="col-lg-4">
        <div class="card mb-4">
          <div class="card-body text-center">
            <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava3.webp" alt="avatar"
              class="rounded-circle img-fluid" style="width: 150px;">
            <h5 class="my-3"><%= @user.first_name + ' ' + @user.last_name %></h5>
            <p class="text-muted mb-1"><%= @user.email %></p>
            <p class="text-muted mb-4"><%= @user.phone_number %></p>
            <div class="d-flex justify-content-center mb-2">
              <%= button_to 'Edit', edit_user_registration_path(@user), method: :get, class: "btn btn-primary" %></td>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-8">
        <%= render 'address', address: @address, edit_link: edit_address_path(@address) %>
        <%= render 'credit_card', credit_card: @credit_card %>
      </div>
    </div>
  </div>
</section>