config/routes.rb
Rails.application.routes.draw do
  resources :credit_cards
  resources :addresses
  resources :orders
  resources :categories
  resources :products
  devise_for :users, controllers: { registrations: 'user/registrations' }
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'extra#index'

  get 'show_products', to: 'extra#show_products'
  get 'accounts', to: 'users#index', as: "users"
  get 'my_account', to: 'users#show'
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products # Category.first.products
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin
  before_action :set_category, only: %i[ show edit update destroy ]
  
  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:id, :name, :description, :image_url)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
</div>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <div class="form-outline mb-4">
    <%= f.text_field :name, autofocus: true, required: true, class: "form-control", placeholder: "Name"%>
  </div>
  <br>
  <div class="form-outline mb-4">
    <%= f.text_area :description, autofocus: true, required: true, class: "form-control", placeholder: "Description"%>
  </div>
  <br>
  <div class="form-outline mb-4">
    <%= f.text_field :image_url, required: true, class: "form-control", placeholder: "Image URL"%>
  </div>
  <br>

  <div class="actions">
    <%= f.submit button_text, class: "btn btn-primary btn-block mb-4" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", button_text: "Update" %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<div class="container mt-5">
  <h2>Categories</h2>
  <br>
  <table class="table table-info table-striped">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Name</th>
          <th scope="col">Description</th>
          <th scope="col">Products</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @categories.each do |category| %>
          <tr>
            <td><%= category.id %></td>
            <td><%= category.name %></td>
            <td><%= category.description %></td>
            <td><%= link_to "View #{category.products.count} Products", products_path(category_id: category.id) %></td>
            <td><%= link_to 'Show', category %> | <%= link_to 'Edit', edit_category_path(category) %> | <%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= link_to 'New Category', new_category_path %>
</div>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', button_text: "Create" %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <%= image_tag @category.image_url, class: "d-block w-100" %>
    <h5 class="card-title"><%= @category.name %></h5>
    <p class="card-text"><%= @category.description %></p>
    <%= link_to 'Edit', edit_category_path(@category), class: "btn btn-primary" %>
  </div>
</div>

<%= link_to 'Back', categories_path %>