config/routes.rb
Rails.application.routes.draw do
  resources :credit_cards
  resources :addresses
  resources :orders
  resources :categories
  resources :products
  devise_for :users, controllers: { registrations: 'user/registrations' }
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'extra#index'

  get 'show_products', to: 'extra#show_products'
  get 'accounts', to: 'users#index', as: "users"
  get 'my_account', to: 'users#show'
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :category #Product.fisrt.category
    has_one_attached :image
    has_many :orders
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin
  before_action :set_product, only: %i[ show edit update destroy ]
  
  include Pagy::Backend
  # GET /products or /products.json
  def index
    products = Product.includes(:category).all
    products = products.where(category_id: params[:category_id]) if params[:category_id].present?
    products = products.where(color: params[:color]) if params[:color].present?
    products = products.where("name LIKE ? OR description LIKE ?","%#{params[:search]}%","%#{params[:search]}%") if params[:search].present?
    products = products.order(:name)
    @pagy, @products = pagy(products)
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:id, :name, :description, :sku, :stock, :price, :size, :brand, :color, :image, :category_id)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_filter_menu.html.erb
<!-- _filter_menu.html.erb -->
<%= form_tag products_path, method: :get, class: 'form-inline', id: 'orders-form' do %>

    <%= label_tag :category_id, 'Filter by category:' %>
    <%= select_tag :category_id, options_for_select(Category.all.pluck(:name, :id), params[:category_id]), prompt: 'All'%>

    <%= label_tag :color, 'Filter by color:' %>
    <%= select_tag :color, options_for_select(Product.distinct.pluck(:color).sort, params[:color]), prompt: 'All'%>

    <%= text_field_tag(:search, params[:search]) %>

    <%= submit_tag 'Filter', class: 'btn btn-primary mb-2' %>

<% end %>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <div class="form-outline mb-4">
    <%= f.text_field :name, autofocus: true, required: true, class: "form-control", placeholder: "Name"%>
  </div>
  <br>
  <div class="form-outline mb-4">
    <%= f.text_area :description, required: true, class: "form-control", placeholder: "Description"%>
  </div>
  <br>
  <div class="form-outline mb-4">
    <%= f.text_field :sku, required: true, class: "form-control", placeholder: "SKU"%>
  </div>
  <br>
  <div class="form-outline mb-4">
    <%= f.number_field :stock, min: 0, required: true, class: "form-control", placeholder: "Stock"%>
  </div>
  <br>
  <div class="form-outline mb-4">
    <%= f.number_field :price, min: 0, step: 0.01, required: true, class: "form-control", placeholder: "Price"%>
  </div>
  <br>
  <div class="form-outline mb-4">
    <%= f.number_field :size, min: 0, step: 0.01, required: true, class: "form-control", placeholder: "Size"%>
  </div>
  <br>
  <div class="form-outline mb-4">
    <%= f.text_field :brand, required: true, class: "form-control", placeholder: "Brand"%>
  </div>
  <br>
  <div class="form-outline mb-4">
    <%= f.text_field :color, required: true, class: "form-control", placeholder: "Color"%>
  </div>
  <br>
  <div class="form-outline mb-4">
    <%= f.file_field :image, class: "form-control", placeholder: "Image"%>
  </div>
  <br>
  <div class="form-outline mb-4">
    <%= f.collection_select(:category_id, Category.all, :id, :name, {:include_blank => "Select..."} , {:required => true, :class => "form-select"}) %>
  </div>
  <br>

  <div class="actions">
    <%= f.submit button_text, class: "btn btn-primary btn-block mb-4" %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div id="<%= dom_id product %>">
</div>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render "form", button_text: "Update" %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<div class="container mt-5">
  <h2>Products</h2>
  <br>
  <%= render "filter_menu" %>
  <%==pagy_info(@pagy)%>
  <br>
  <table class="table table-danger table-striped">
      <thead>
        <tr>
          <th scope="col">ID</th>
          <th scope="col">Name</th>
          <th scope="col">Description</th>
          <th scope="col">SKU</th>
          <th scope="col">Stock</th>
          <th scope="col">Price</th>
          <th scope="col">Size</th>
          <th scope="col">Brand</th>
          <th scope="col">Color</th>
          <th scope="col">Category</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @products.each do |product| %>
          <tr>
            <td><%= product.id %></td>
            <td><%= product.name %></td>
            <td><%= product.description %></td>
            <td><%= product.sku %></td>
            <td><%= product.stock %></td>
            <td><%= product.price %></td>
            <td><%= product.size %></td>
            <td><%= product.brand %></td>
            <td><%= product.color %></td>
            <td><%= product.category.name %></td>
            <td><%= link_to 'Show', product %> | <%= link_to 'Edit', edit_product_path(product) %> | <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= link_to 'New Product', new_product_path %>
    <%== pagy_nav(@pagy) if @pagy.pages > 1 %>
</div>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", button_text: "Create" %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <%= image_tag @product.image, class: "d-block w-100" %>
    <h5 class="card-title"><%= @product.name %></h5>
    <p class="card-text"><%= @product.description %></p>
    <p class="card-text">Color: "<%= @product.color %>"</p>
    <p class="card-text">Price: <%= @product.price %>$</p>
    <p class="card-text">Size: <%= @product.size %></p>
    <%= link_to 'Edit', edit_product_path(@product), class: "btn btn-primary" %>
  </div>
</div>

<%= link_to 'Back', products_path %>