config/routes.rb
Rails.application.routes.draw do
  resources :credit_cards
  resources :addresses
  resources :orders
  resources :categories
  resources :products
  devise_for :users, controllers: { registrations: 'user/registrations' }
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'extra#index'

  get 'show_products', to: 'extra#show_products'
  get 'accounts', to: 'users#index', as: "users"
  get 'my_account', to: 'users#show'
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
  <%= link_to root_path, class: "navbar-brand", id: "logo" do %>
    <%= image_tag "logo.jpeg", style: "max-height: 30px; vertical-align: middle; margin-right: 5px;vertical-align: -7px;" %>
    HoopHaven
    <% end %> 
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if current_user.present? %>
          <% if current_user.admin? %>
            <li class="nav-item"><%= link_to "Users", users_path, class: "nav-link butoane-nav" %></li>
            <li class="nav-item"><%= link_to "Categories", categories_path, class: "nav-link butoane-nav" %></li>
            <li class="nav-item"><%= link_to "Products", products_path, class: "nav-link butoane-nav" %></li>
            <li class="nav-item"><%= link_to "Orders", orders_path, class: "nav-link butoane-nav" %></li>
            <% else %>
            <li class="nav-item"><%= link_to "My Account", my_account_path, class: "nav-link butoane-nav" %></li>
            <li class="nav-item"><%= link_to "My Orders", orders_path(user_id: current_user.id), class: "nav-link butoane-nav" %></li>
          <% end %>
          <li class="nav-item"><%= link_to 'Logout', destroy_user_session_path, data:{turbo_method: :delete}, class: 'nav-link butoane-nav' %></li>
        <% else %>
          <li class="nav-item"><%= link_to "Log in", new_user_session_path, class: "nav-link butoane-nav" %></li>
        <% end %>
      </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OnlineShop</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <% if notice.present? %>
      <div class="alert alert-success" role="alert">
        <%= notice %>
      </div>
    <% end %>
    <% if alert.present? %>
      <div class="alert alert-danger" role="alert">
        <%= alert %>
      </div>
    <% end %>
    <div class="background-overlay"></div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>